import React from "react";
import { dir } from "i18next";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Dancing_Script } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { Providers } from "@/components/wrapper/Providers";
import { AuthenticationWrapper } from "@/components/wrapper/AuthenticationWrapper";
import { AppIcon, CustomText } from "@/components";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/nextAuth";
// import { LogoutButton } from "../../../components/LogoutButton";

const MPLUS1Code = localFont({
  src: "../fonts/MPLUS1Code-Regular.ttf",
  variable: "--m-plus-1code",
  weight: "100 900",
});

const DancingScriptFont = Dancing_Script({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "meditation app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{ children: React.ReactNode; params: { lang: string } }>) {
  // AuthJSのセッションからユーザー情報を取得
  const session = await getServerSession(authOptions);
  // セッションからユーザー情報を取得
  const userName = session?.user?.name;
  const userId = session?.user?.id;
  const userImage = session?.user?.image;

  console.log("Session data:", session);
  console.log("User name:", userName);
  console.log("User ID:", userId);

  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={`${MPLUS1Code.variable} p-0 m-0`}>
        <Providers lang={lang}>
          <AuthenticationWrapper>
            <header className="flex justify-between border-b-purple-200 border-b-2 px-4 pt-[5px]">
              <AppIcon id="app-icon" className={DancingScriptFont.className} />
              <div className="m-0 p-2 text-center text-purple-200">
                <Link href={`/${lang}/meditation`} className="">
                  <h1 className="text-4xl">Meditation App</h1>
                </Link>
              </div>
              <div
                data-testid="avator-icon"
                className="flex flex-col items-center"
              >
                {userImage ? (
                  <Image
                    width={50}
                    height={50}
                    className="rounded-full border-purple-300 border-2"
                    src={userImage}
                    alt="user-avatar"
                  />
                ) : (
                  <div className="w-12 h-12 bg-purple-200 rounded-full flex items-center justify-center">
                    <CustomText text={userName?.charAt(0) ?? "Guest"} />
                  </div>
                )}
                <div className="text-xs text-center mt-1 text-purple-200">
                  <CustomText text={userName ?? "Guest"} />
                </div>
                {/* <LogoutButton className="mt-1" /> */}
              </div>
            </header>
            {children}
          </AuthenticationWrapper>
        </Providers>
      </body>
    </html>
  );
}
