import React from "react";
import { dir } from "i18next";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Dancing_Script } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { LanguageProvider } from "@/i18n/client";
import { AppIcon, CustomText } from "@/components";
import Link from "next/link";

const MPLUS1Code = localFont({
  src: "../fonts/MPLUS1Code-Regular.ttf",
  variable: "--m-plus-1code",
  weight: "100 900",
});

const DancingScriptFont = Dancing_Script({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "meditation app",
  description: "Generated by create next app",
};

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const user = {
  login: "YoichiIshigaki",
  id: 50575636,
  node_id: "MDQ6VXNlcjUwNTc1NjM2",
  avatar_url: "https://avatars.githubusercontent.com/u/50575636?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/YoichiIshigaki",
  html_url: "https://github.com/YoichiIshigaki",
  followers_url: "https://api.github.com/users/YoichiIshigaki/followers",
  following_url:
    "https://api.github.com/users/YoichiIshigaki/following{/other_user}",
  gists_url: "https://api.github.com/users/YoichiIshigaki/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/YoichiIshigaki/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/YoichiIshigaki/subscriptions",
  organizations_url: "https://api.github.com/users/YoichiIshigaki/orgs",
  repos_url: "https://api.github.com/users/YoichiIshigaki/repos",
  events_url: "https://api.github.com/users/YoichiIshigaki/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/YoichiIshigaki/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  name: "YoichiIshigaki",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio:
    "main:\r\n" +
    "Frontend Engineer\r\n" +
    "Laravel,Python,React,Node.js,Terraform,Typescript etc",
  twitter_username: null,
  public_repos: 18,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2019-05-13T09:11:26Z",
  updated_at: "2024-09-28T07:08:13Z",
};

type GithubUser = typeof user;

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const getGithubUser = async (username: string): Promise<GithubUser> => {
    const res = await fetch(`https://api.github.com/users/${username}`);
    const json = await res.json();
    return json as GithubUser;
  };

  const userName = "YoichiIshigaki";
  const githubUser = await getGithubUser(userName);

  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={`${MPLUS1Code.variable} p-0 m-0`}>
        <LanguageProvider initialLanguage={lang}>
          <header className="flex justify-between border-b-purple-200 border-b-2 px-4 pt-[5px]">
              <AppIcon id="app-icon" className={DancingScriptFont.className} />
            <div className="m-0 p-2 text-center text-purple-200">
              <Link href={`/${lang}/meditation`} className="">
                <h1 className="text-4xl">Meditation App</h1>
              </Link>
            </div>
            <div data-testid="avator-icon">
              {githubUser.avatar_url ? (
                <Image
                  width={50}
                  height={50}
                  className="rounded-full border-purple-300 border-2"
                  src={githubUser.avatar_url}
                  alt="avator-icon"
                />
              ) : (
                <CustomText text={"ログイン"}  />
              )}
            </div>
          </header>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
