import React from "react";
import { dir } from "i18next";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { LanguageProvider } from "@/i18n/client";

const MPLUS1Code = localFont({
  src: "../fonts/MPLUS1Code-Regular.ttf",
  variable: "--m-plus-1code",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "meditation app login",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  console.log("RootLayout lang:", lang);
  // Ensure lang is a valid language code
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={`${MPLUS1Code.variable} p-0 m-0`}>
        <LanguageProvider initialLanguage={lang}>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
