import React from "react";
import { dir } from "i18next";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Providers } from "@/components/wrapper/Providers";
import { AuthenticationWrapper } from "@/components/wrapper/AuthenticationWrapper";

const MPLUS1Code = localFont({
  src: "../fonts/MPLUS1Code-Regular.ttf",
  variable: "--m-plus-1code",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "meditation app login",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${MPLUS1Code.variable} p-0 m-0`}>
        <Providers lang={lang}>
          <AuthenticationWrapper>
            {children}
          </AuthenticationWrapper>
        </Providers>
      </body>
    </html>
  );
}
