services:
  localstack-aws:
    container_name: local-aws
    image: localstack/localstack:3.8.1
    ports:
      - 4566:4566 # s3
      - 8082:8080 # dashboard 有料版のみ使用可能
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_SOCK=/var/run/docker.sock  # locakstackでもローカルDocker利用できるようにする設定
      - DEBUG=1                           # トラブルシューティングに役立つため、DEBUGログをonに設定
    volumes:
      - local-aws:/var/lib/localstack/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./local_script:/etc/localstack/init/ready.d  # localstackのDocker起動時に実行される.shスクリプトの置き場
    networks:
      local-aws-network:
  minio:
    image: "minio/minio:RELEASE.2023-01-02T09-40-09Z.fips"
    container_name: s3-minio-container
    volumes:
      - "./minio/data:/data:delegated"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY[=MINIO_ROOT_USER]
      - MINIO_SECRET_KEY[=MINIO_ROOT_PASSWORD]
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_SERVER_URL=http://localhost:9000
    command: server /data --console-address :9001
    # aws s3 ls --endpoint-url=http://localhost:9000  --profile minio meditation-app --recursive
  # mybucket バケット作成
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 user password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/meditation-app;
      /usr/bin/mc policy download myminio/meditation-app;
      exit 0;
      "


networks:
  local-aws-network:
volumes:
  local-aws: